#!ruby
require 'fileutils'
require 'shellwords'
include FileUtils

def get_first_non_comment_line(f)
  return File.read(f).split("\n").find{|l| l[0]!="#"} if File.exists?(f)
  return false
end

folder = pwd().split("/")
done = false

loop do
	# get the context
	context = get_first_non_comment_line(File.join(folder, ".k_context"))

	# get the namespace
	namespace = get_first_non_comment_line(File.join(folder, ".k_namespace"))

	if context && namespace
		puts "K8s --> context: #{context}, namespace: #{namespace}"
		`kubectl config use-context #{Shellwords.escape(context)} --namespace=#{Shellwords.escape(namespace)}`
		done = true
	elsif context
		puts "K8 --> context: #{context}"
		`kubectl config use-context #{Shellwords.escape(context)}`
		done = true
	elsif namespace
		puts "K8 --> namespace: #{namespace}"
		`kubectl config set-context --current --namespace=#{Shellwords.escape(namespace)}`
		done = true
	end

	 folder.pop()

	 break if folder.empty? || done 
end